name: Build & deploy staging

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-staging:
    name: Build-staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  deploy-staging:
    name: Deploy staging
    needs: build-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: ./staging
        cname: wallet.ambire.com
  build-relayrless:
    name: Build-Relayrless
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      env:
        REACT_APP_RELAYRLESS: true
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      env:
        REACT_APP_RELAYRLESS: true
      run: npm ci
    
    - name: Build project
      env:
          REACT_APP_RELAYRLESS: true
      run: npm run build
    
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      env:
        REACT_APP_RELAYRLESS: true
      with:
        name: production-files
        path: ./build
  deploy-relayerless:
    name: Deploy relayerless
    needs: build-relayrless
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/relayerless'
    steps:
    - name: Download artifact
      env:
          REACT_APP_RELAYRLESS: true
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      env:
        REACT_APP_RELAYRLESS: true
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: ./relayerless
        cname: wallet.ambire.com
